version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: harmonify
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: npm run start:dev
    volumes:
      - ./backend:/app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/harmonify?schema=public

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  db-data: